<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\HomeController
 */
class HomeControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function history_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $set = \App\Models\Set::factory()->create();
        $tests = \App\Models\Test::factory()->times(3)->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->get(route('test-history', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('history');
        $response->assertViewHas('tests', $tests);
        $response->assertViewHas('set', $set);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $sets = \App\Models\Set::factory()->times(3)->create();
        $tests = \App\Models\Test::factory()->times(3)->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->get(route('home'));

        $response->assertOk();
        $response->assertViewIs('home');
        $response->assertViewHas('sets', $sets);
        $response->assertViewHas('incomplete');

        // TODO: perform additional assertions
    }

    // test cases...
}
